#ifndef CONVDECFRACCORE_GLOBAL_H
#define CONVDECFRACCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(CONVDECFRACCORE_LIBRARY)
#  define CONVDECFRACCORESHARED_EXPORT Q_DECL_EXPORT
#else
#  define CONVDECFRACCORESHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // CONVDECFRACCORE_GLOBAL_H
